version: '3'
volumes:
  dados:
networks:
  banco:
  web:
services:
  db:
    image: postgres:9.6
    volumes:
      # Volume dos dados -> armazenamento gerenciado pelo proprio docker
      - dados:/var/lib/postgresql/data
      # Scripts -> referencia para a pasta local
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql # script de inicializacao do banco de dados
    environment:
      POSTGRES_PASSWORD: "teste123"
    networks:
        - banco
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
    depends_on:
      - db